apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraformAKSACR
  annotations:
    github.com/project-slug: prayankag/terraformAKSACR
   spec:
  type: service
  lifecycle: Testing
  owner: prayankag
